version: '3'

services:
    server:
      build: nginx/.
      ports:
        - 3000:80
    node1:
      build: .
      ports:
        - 3001:8081
      environment: 
        MSG: Junaid 
    node2:
      build: .
      ports:
        - 3002:8081
      environment:
        MSG: zubair    