version: '3'

services:
  dev:
    build: .
    volumes:
      - .:/usr/src/app/
      -  /usr/src/app/node_modules
    ports: 
      - 3001:3000
    depends_on:
      - db
  db:
      image: mongo
      restart: always
      volumes:
        - data-volume:/data/db
      # ports:
      # - 27017:27017
volumes:
  data-volume: