version: '3'

services:
  dev:
    build: .
    volumes:
      - .:/usr/src/app/
      -  /usr/src/app/node_modules
    ports: 
      - 3002:3002
    depends_on:
      - db
  db:
      image: mongo
      restart: always
      volumes:
        - data-volume:/data/db
volumes:
  data-volume: